[package]
name = "ros2-grpc-bridge"
version = "0.1.0"
edition = "2024"

[dependencies]
tokio = { version = "1", features = ["macros", "rt-multi-thread"] }
tonic = "0.14"
tonic-web = "0.14"
prost = "0.14"
tonic-prost = "0.14"
tonic-reflection = "0.14.6"
tower-http = {version = "0.6", features = ["cors"]}
rclrs = "0.7"
sensor_msgs = {
    path = "/opt/ros/jazzy/share/sensor_msgs/rust"
}

[build-dependencies]
tonic-prost-build = "0.14"
